


console.log("hello");
try{
let x= 5;
console.log(x());
}catch(error){
console.log(error);
alert(error.message)
}finally{
console.log("I'm done");
}

